import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./hooks/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./types/**/*.{js,ts,jsx,tsx,mdx}",
    "./__tests__/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        cream: {
          50: "#fefdf8",
          100: "#fefbf0",
          200: "#fcf6e1",
          300: "#f9f0d2",
          400: "#f5e9c3",
          500: "#f1e2b4",
          600: "#eddba5",
          700: "#e9d496",
          800: "#e5cd87",
          900: "#e1c678",
        },
        pastel: {
          orange: {
            50: "#fef7f0",
            100: "#fdeee0",
            200: "#fbd9c1",
            300: "#f8c4a2",
            400: "#f5af83",
            500: "#f29a64",
            600: "#e88545",
            700: "#d17026",
            800: "#b85b07",
            900: "#9f4600",
          },
          green: {
            50: "#f5f9f6",
            100: "#e8f2eb",
            200: "#d1e5d7",
            300: "#bad8c3",
            400: "#a3cbaf",
            500: "#8cbe9b",
            600: "#75b187",
            700: "#5ea473",
            800: "#47975f",
            900: "#308a4b",
          },
          purple: {
            50: "#f7f5f9",
            100: "#ede9f2",
            200: "#dcd3e5",
            300: "#cbbdd8",
            400: "#baa7cb",
            500: "#a991be",
            600: "#987bb1",
            700: "#8765a4",
            800: "#764f97",
            900: "#65398a",
          },
          blue: {
            50: "#f0f4f7",
            100: "#d9e4ed",
            200: "#c2d4e3",
            300: "#abc4d9",
            400: "#94b4cf",
            500: "#7da4c5",
            600: "#6694bb",
            700: "#4f84b1",
            800: "#3874a7",
            900: "#21649d",
          },
          pink: {
            50: "#f9f5f7",
            100: "#f0e6ed",
            200: "#e1cddd",
            300: "#d2b4cd",
            400: "#c39bbd",
            500: "#b482ad",
            600: "#a5699d",
            700: "#96508d",
            800: "#87377d",
            900: "#781e6d",
          },
          yellow: {
            50: "#faf8f0",
            100: "#f4f0e0",
            200: "#e8e1c1",
            300: "#dcd2a2",
            400: "#d0c383",
            500: "#c4b464",
            600: "#b8a545",
            700: "#ac9626",
            800: "#a08707",
            900: "#947800",
          },
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
export default config
